In [268]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [269]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [339]:
examenes = pd.read_csv('exams.csv')

In [340]:
examenes

gender race/ethnicity parental level of education         lunch  \
0      male        group A                 high school      standard   
1    female        group D            some high school  free/reduced   
2      male        group E                some college  free/reduced   
3      male        group B                 high school      standard   
4      male        group E          associate's degree      standard   
..      ...            ...                         ...           ...   
995    male        group C                 high school      standard   
996    male        group D          associate's degree  free/reduced   
997  female        group C            some high school  free/reduced   
998  female        group C                some college      standard   
999    male        group A                some college      standard   

    test preparation course  math score  reading score  writing score  
0                 completed          67             67             63  
1                      none          40             59             55  
2                      none          59             60             50  
3                      none          77             78             68  
4                 completed          78             73             68  
..                      ...         ...            ...            ...  
995                    none          73             70             65  
996               completed          85             91             92  
997                    none          32             35             41  
998                    none          73             74             82  
999               completed          65             60             62  

[1000 rows x 8 columns]

In [341]:
examenes_categoricas = examenes.loc[:,["gender", "race/ethnicity", "parental level of education", "lunch", "test preparation course"]]

In [342]:
examenes_categoricas

gender race/ethnicity parental level of education         lunch  \
0      male        group A                 high school      standard   
1    female        group D            some high school  free/reduced   
2      male        group E                some college  free/reduced   
3      male        group B                 high school      standard   
4      male        group E          associate's degree      standard   
..      ...            ...                         ...           ...   
995    male        group C                 high school      standard   
996    male        group D          associate's degree  free/reduced   
997  female        group C            some high school  free/reduced   
998  female        group C                some college      standard   
999    male        group A                some college      standard   

    test preparation course  
0                 completed  
1                      none  
2                      none  
3                      none  
4                 completed  
..                      ...  
995                    none  
996               completed  
997                    none  
998                    none  
999               completed  

[1000 rows x 5 columns]

In [343]:
frec = examenes_categoricas.groupby(['gender']).count()

In [344]:
examenes['gender_num'] = np.where(examenes['gender'] == 'male',1,2)


In [345]:
frec = examenes_categoricas.groupby(['race/ethnicity']).count()

In [346]:
examenes['race_num'] = np.where(examenes['race/ethnicity'] == 'group C', 1, np.where(examenes['race/ethnicity'] == 'group D', 2, 3))

In [347]:
frec = examenes_categoricas.groupby(['parental level of education']).count()

In [348]:
examenes['parental_num'] = np.where(examenes['parental level of education'] == 'some college', 1, np.where(examenes['parental level of education'] == "associate's degree",2,3))

In [349]:
frec = examenes_categoricas.groupby(['lunch']).count()

In [350]:
examenes['lunch_num'] = np.where(examenes['lunch'] == 'standard', 1, 2)

In [351]:
frec = examenes_categoricas.groupby(['test preparation course']).count()

In [352]:
examenes['test_prep'] = np.where(examenes['test preparation course'] == 'none', 1, 2)
examenes['Probabilidad_'] = np.where(examenes['math score'] > 60,1,0)
examenes = examenes.loc[:,['gender_num', 'race_num', 'parental_num', 'lunch_num','test_prep', 'reading score', 'writing score','Probabilidad_']]
examenes

gender_num  race_num  parental_num  lunch_num  test_prep  reading score  \
0             1         3             3          1          2             67   
1             2         2             3          2          1             59   
2             1         3             1          2          1             60   
3             1         3             3          1          1             78   
4             1         3             2          1          2             73   
..          ...       ...           ...        ...        ...            ...   
995           1         1             3          1          1             70   
996           1         2             2          2          2             91   
997           2         1             3          2          1             35   
998           2         1             1          1          1             74   
999           1         3             1          1          2             60   

     writing score  Probabilidad_  
0               63              1  
1               55              0  
2               50              0  
3               68              1  
4               68              1  
..             ...            ...  
995             65              1  
996             92              1  
997             41              0  
998             82              1  
999             62              1  

[1000 rows x 8 columns]

In [353]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix, roc_curve

In [354]:
features_col = examenes.columns.values[0:7]

In [356]:
X = examenes[features_col].values
Y = examenes["Probabilidad_"].values

In [357]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.30, random_state = 0)

In [358]:
log_model = LogisticRegression(solver='lbfgs', max_iter=1000)
log_model.fit(X_train,Y_train)

LogisticRegression(max_iter=1000)

In [359]:
y_pred = log_model.predict(X_test)

In [360]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [361]:
Y_test

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1])

In [362]:
log_model.predict_proba(X_test)[:,1]

array([1.28475760e-01, 9.23926256e-01, 4.51628225e-01, 9.43765851e-01,
       5.94735572e-04, 8.76355228e-02, 9.40114494e-01, 9.96489635e-01,
       9.55412998e-01, 9.99968525e-01, 6.18531280e-06, 9.88047724e-01,
       9.91337087e-01, 9.92296115e-01, 8.81136311e-01, 5.56222775e-02,
       9.87922420e-01, 5.00687838e-02, 9.99727491e-01, 9.71686600e-01,
       9.93246649e-01, 9.74559576e-01, 8.91264056e-01, 2.70852717e-02,
       9.90234180e-01, 9.20234715e-01, 3.68926182e-01, 9.88637553e-01,
       2.98061114e-01, 1.39684197e-02, 9.80119329e-01, 1.92702086e-01,
       4.47639953e-01, 9.74022448e-01, 9.10942751e-02, 9.99784900e-01,
       3.37612856e-01, 4.64888178e-02, 9.86719642e-01, 9.72642565e-01,
       9.81282553e-01, 9.99813813e-01, 9.99605144e-01, 9.72762883e-01,
       9.95603095e-01, 5.44091381e-01, 5.04578063e-01, 9.77984345e-01,
       1.04629599e-01, 9.99427514e-01, 8.24683571e-01, 9.97517153e-01,
       3.97392348e-01, 6.31276963e-01, 9.98993445e-01, 7.46867204e-01,
      

In [363]:
print(metrics.accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test,y_pred))

0.89
0.9238578680203046
0.91
0.9168765743073047


In [364]:
###Neuronal Network

In [365]:
from sklearn.neural_network import MLPClassifier

from sklearn import metrics
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix, roc_curve

In [366]:
x_train = X_train
x_test = X_test
y_train = Y_train
y_test = Y_test

In [367]:
NN = MLPClassifier(random_state=1, max_iter=3000)

NN.fit(x_train, y_train)

y_pred = NN.predict(x_test)


accuracy = accuracy_score(y_test,y_pred) * 100
confusion_mat = confusion_matrix(y_test,y_pred)

In [368]:
print(metrics.accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test,y_pred))

0.8866666666666667
0.9322916666666666
0.895
0.913265306122449


In [369]:
##Arbol de desiciones

In [370]:
from sklearn import tree

In [371]:
tree_one = tree.DecisionTreeClassifier(random_state=1)

In [372]:
tree_one = tree_one.fit(x_train, y_train)

In [373]:
tree_one.tree_.max_depth

12

In [374]:
y_pred = tree_one.predict(x_test)

In [375]:
print(metrics.accuracy_score(y_test, y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))

0.87
0.900497512437811
0.905
0.9027431421446384
